### ISSUE TITLE
remainder reserved word

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/Simple-Libraries#176]
Naming a variable "remainder" throws this compiler error

![image](https://user-images.githubusercontent.com/22827298/45720598-aafd2380-bb59-11e8-8b83-ae81fc1b715e.png)

![image](https://user-images.githubusercontent.com/22827298/45720570-93be3600-bb59-11e8-8580-a953066d019e.png)

**Comment by Steph-Parallax** [comment]
Generated C.

/* SERIAL_TERMINAL USED */


// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
int quotient;
int remainder;



// ------ Main Program ------
int main() {

  quotient = (10 / 3);
  remainder = (10 % 3);
  print("%s%d%s%d\r", "quotient = ", quotient, " and remainder = ", remainder);

}

**Comment by Steph-Parallax** [comment]
Oh, let me try this in Demo. It may actually be caused by a different bug in the print multiple block that isn't in production yet.

**Comment by Steph-Parallax** [comment]
Tested in Demo, it gets the same error message. So it is not related to blocklyprop #1538

**Comment by AndyLindsay** [comment]
This is in Propeller GCC
#define remainder(x,y)   __TGMATH_REAL_2(x, y, remainder)

I'd recommend adding 'remainder' to the reserved words list in blocklyprop.

**Comment by Steph-Parallax** [comment]
Thanks! I'll open an issue over there and link to this.
