### ISSUE TITLE
Renaming this GitHub to something more appropriate

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/Simple-Libraries#28]
At present this GitHub is named propsideworkspace. The name is not descriptive of the libraries we are trying to maintain and probably not an effective name to try to attract other contributors to our little ecosystem. 

I suggest something along the lines of SimpleIDE_Libraries. 

Can you do this @PropGit?

**Comment by AndyLindsay** [comment]
Done, thanks PropGit!
