### ISSUE TITLE
libcolormath.a file rename

### ISSUE THREAD

**Issue by zfi** [parallaxinc/Simple-Libraries#35]
The color library libcolormath.a is currently named as libcolorMath.a (note the uppercase M). The cloud compiler generates an error that states that the libcolormath.a file cannot be found.  Changing the name of the library on the cloud compiler server to incorporate the lower case 'm' resolves the error.

Please correct the library name in the build process.

**Comment by PropGit** [comment]
Thanks @zfi.  Fixed in both master and BlocklyProp branches.
