### ISSUE TITLE
Please add some math functions

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/Simple-Libraries#37]
We could use a few functions, similar to what's available in Arduino:

map(); - https://www.arduino.cc/en/Reference/Map
constrain(); - https://www.arduino.cc/en/Reference/constrain
max(); - https://www.arduino.cc/en/Reference/Max
min(); - https://www.arduino.cc/en/Reference/Min

**Comment by PropGit** [comment]
min and max are not in the Standard C Library?

**Comment by MatzElectronics** [comment]
I don't believe so.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
This is working - we can close the issue.
