### ISSUE TITLE
simpletext writeStr does not appear to send terminating char

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/Simple-Libraries#39]
When I used writeStr() and readStr() together, I had to send a send a 0 (null) character after the string.  Otherwise readStr() filled it's limit with the send string in a sort of loop.

**Comment by AndyLindsay** [comment]
A terminating character should be appended to the string that gets sent, typically \r or \n.  This keeps writeStr compatible with more receiving devices.  By automatically adding a 0 to the string that gets sent, it would interfere with devices that expect \n or \r but for which \0x0 has a different meaning.

**Comment by AndyLindsay** [comment]
P.S. Off the top of my head, examples of receiving devices where 0x00 has another meaning include the Parallax Serial LCD, XBee, and Parallax software terminals.

**Comment by MatzElectronics** [comment]
Good to know.  It's easy to just append the zero.

**Comment by MatzElectronics** [comment]
Go ahead and close the issue...  I know now how I want to handle this.
Thanks!

**Comment by AndyLindsay** [comment]
Okay, thanks Matt.
